server:
  port: 8002
    
spring:
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://192.168.100.75:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.auggie.dubbo